#!/usr/bin/env bash
set -ex

OUT=target/

MODEL=cpp17

if [ ! -z "$1" ]; then
   MODEL=$1
fi

CONF=model/${MODEL}.cfg

if [ ${MODEL} = "multi" ]; then
    CONF=model/cpp17.cfg
    CONF11=model/cpp11.cfg
    for f in `find tests -name "*.litmus" -type f`; do
	if [[ ${f} == *"cpp11"* ]]; then
	    herd7  -o ${OUT} -conf ${CONF11} -timeout none ${f} &> ${f}.expected &
	else
	    herd7  -o ${OUT} -conf ${CONF} -timeout none ${f} &> ${f}.expected &
	fi
    done
else
    for f in `find tests -name "*.litmus" -type f`; do
	herd7  -o ${OUT} -conf ${CONF} -timeout none ${f} &> ${f}.expected &
    done
fi

wait

for f in `find tests -name "*.litmus" -type f`; do
    sed -i  '' '/^Time/d' ${f}.expected &
done

wait
